export const ICONS = {
  ROBOT: '🤖',
  CALENDAR: '📅',
  CONVERSATION: '💬',
  SUMMARY: '📝',
  HOME: '🏠',
  TIME: '⏰',
  EXCHANGE: '🔄',
  CODE: '💻',
  TAG: '🏷️',
  HIGHLIGHT: '✨',
  TOPIC: '🏷️',
  ARROW_RIGHT: '→',
  ARROW_LEFT: '←',
  SEPARATOR: '>',
};

export const LABELS = {
  CONVERSATIONS: 'conversations',
  EXCHANGES: 'exchanges',
  TOPICS: 'topics',
  WITH_CODE: 'with code',
  CODE_INCLUDED: 'Code included',
  READ_FULL: 'Read Full →',
  BACK_TO: 'Back to',
  ALL_DAYS: 'All Days',
  HOME: 'Home',
  DAILY_SUMMARY: 'Daily Summary',
  DAILY_CONVERSATIONS: 'Daily conversations and insights',
  NO_CONTENT_FOUND: 'No content found for',
  START_BY_ADDING: 'Start by adding files to',
};
