name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: 'package.json'

      - name: Install dependencies
        run: bun install --frozen-lockfile

      - name: Check formatting
        run: bun format:check

      - name: Run linter
        run: bun lint

      - name: Run textlint
        run: bun textlint

      - name: Build
        run: bun run build
